### ISSUE TITLE
0.3.10 throws Exception in callback of async function.. same code works in 0.3.9...

### ISSUE THREAD

**Issue by sunkay** [xolvio/meteor-cucumber#48]
0.3.10 throws this exception:
Exception in callback of async function: TypeError: object is not a function
at /Users/sunil/meteor/meteor-boiler/tests/cucumber/features/support/hooks.js:45:7
at runWithEnvironment (/Users/sunil/meteor/meteor-boiler/.meteor/local/build/programs/server/packages/meteor.js:1052:24)

My before hook is fairly simple. This exception happens at callback().

My before hook:

this.Before("@beforeHookLogin", function(callback){
  console.log("start @beforeHookLogin");
  //always signout before sigingin in
  helper.world.browser.
    url(helper.world.cucumber.mirror.rootUrl).
    waitForExist('#at-nav-button').
    waitForVisible('#at-nav-button').
    click('#at-nav-button');

  // make sure the user is Authenticated
  helper.world.browser.
    url(helper.world.cucumber.mirror.rootUrl+"sign-in").
    waitForExist('.at-pwd-form').
    waitForVisible('.at-pwd-form').
    setValue('#at-field-email', 'sunil@y.com').
    setValue('#at-field-password', 'sunil123').
    click('#at-btn');

  console.log("End @beforeHookLogin");

  callback(); <-- exception happens here
});

**Comment by samhatoum** [comment]
it looks like the first param to the before hook is not a function. Could you run a `console.log(arguments);` right after `console.log("start @beforeHookLogin");` to see what the first parameter is?

**Comment by sunkay** [comment]
This is what it spits out Sam.

{ '0': { [Function] pending: [Function: pending], fail: [Function: fail] } }

I am using the following API as described in the cucumberjs github page:

Tagged hooks

Hooks can be conditionally elected for execution based on the tags of the
scenario.

// features/support/hooks.js (this path is just a suggestion)
var myHooks = function () {
  this.Before("@foo", "@bar,@baz", function(callback) {
    // This hook will be executed before scenarios tagged with @foo and either
    // @bar or @baz.

    // ...

    callback();
  });
};
module.exports = myHooks;

**Comment by samhatoum** [comment]
ok, looks like a bug in meteor-cucumber

**Comment by bar** [comment]
@sunkay Please don't send me this, thanks :)

**Comment by samhatoum** [comment]
@bar you're getting these message probably because you are subscribed to this thread/repo

**Comment by bar** [comment]
@samhatoum not quite... it is because @sunkay summoned me using my GH handle here https://github.com/xolvio/meteor-cucumber/issues/48#issuecomment-75878971

**Comment by sunkay** [comment]
LOL.. just realized that.. no foo bar for you...

**Comment by samhatoum** [comment]
Can you please try with `meteor add xolvio:cucumber@0.6.0-rc.7` please? Please be sure to see the [breaking changes](https://github.com/xolvio/meteor-cucumber#breaking-changes) section.
